main: Jsim.exe randomPermutationsDocuments.exe signatureMinhashSimilarity.exe lhs.exe

Jsim.exe:
	g++ -o Jsim.exe Jsim.cpp

randomPermutationsDocuments.exe:
	g++ -o randomPermutationsDocuments.exe randomPermutationsDocuments.cpp

signatureMinhashSimilarity.exe:
	g++ -o signatureMinhashSimilarity.exe signatureMinhashSimilarity.cpp

lhs.exe:
	g++ -o lhs.exe lhs.cpp

clean:
	rm *.exe
